repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit

- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python -m unittest discover
    language: python
    'types': [python]
    pass_filenames: false
    stages: [commit]

  - id: freeze
    name: freeze
    entry: pip freeze > r.txt
    language: python
